In [2]:
import numpy as np           # to initializze

In [ ]:
l=[1,2,3]

a=np.array(l)                 #   --np.--- is used to use numpy

a

type(a)

numpy.ndarray

Few numpy **functions** for directly generating arrays

In [ ]:
np.random.randint(10)                             # randint generates random integer of given number as limit


1

In [ ]:
for i in range (5):                               # gives 5 random value within 100
  print(np.random.randint(100))

12
73
52
67
35


In [ ]:
np.random.randint(10,50,6)                      # start,stop,no of elements    to print

array([35, 17, 10, 22, 17, 33])

arange function

In [ ]:
np.arange(10)                                   # similar to range but output in the form of array

np.arange(1,10,2)


array([1, 3, 5, 7, 9])

linspace ***function***

In [ ]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
x=np.linspace(10,20,5)

x.ndim                                       #.nd to check its diension


1

In [ ]:
x= np.array([[1,2,3],[6,5,8]])                  # here the dimension it two

x

x.ndim

2

In [ ]:
x.shape

x.size


(2, 3)

empty/zero/ones/full  **  function**

In [ ]:
np.empty([2,1])                                # inside [] bracket it defines rows and column   2 row 1 column            it directly generates array with ready made values


np.zeros([2,1])

np.ones([2,1])                                  #np.ones([2,1],dtype=int)  ----> to change the data type

np.full((2,1), fill_value=9)                  # in fill it is ()   not []


np.identity(3)                               # to create square matrix   with identical diagonal


                          # to create custom diagonal N & M & k should be capital


np.eye(10,5,-5)                              # same but without keyword arguments

array([[1.],
       [1.]])

**three dimensional array**

In [4]:
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[7,8,9],[10,11,12]]])                           #  can contain mreo than this
x

x.ndim                                         # three dimensional array

x.shape                                        #3-levels,,2-rows,3-columns

l=x.reshape(3,6)                                 # to reshape existing rows and columns.
l


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**slicing in array**

In [9]:
ar=np.array([1,2,3,45,6,7,8,9,1,55])


ar[1]


x[0][1][1]                             # fro selecting in 3d

l[1,2]


l[1:1,2:5]                            # for selecting from this to that.....

9

**operations on matrix**

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])


x>5

x[x>5]

array([6, 7, 8, 9])

In [ ]:
x1=np.array([4,85,7,87,6,4,54])

x2=np.array([98,57,1,5,6,74,5])

x1+x2                                 # adds element with element

x1-x2

x1*x2

x1**2

array([  16, 7225,   49, 7569,   36,   16, 2916])

In [ ]:
# Power function


np.power(x1,2)

array([  16, 7225,   49, 7569,   36,   16, 2916])

In [ ]:
y1=np.array([[4,85,7],[5,25,69]])

y2=np.array([[5,1,4],[1,56,6]])


y1*y2                         # this procedure multiplies the element like same as of the 1d


array([[  20,   85,   28],
       [   5, 1400,  414]])

In [ ]:
y1

array([[ 4, 85,  7],
       [ 5, 25, 69]])

In [ ]:
y2

array([[ 5,  1,  4],
       [ 1, 56,  6]])

In [ ]:
y3=y2.reshape(3,2)
y3

array([[ 5,  1],
       [ 4,  1],
       [56,  6]])

In [ ]:
y1.dot(y3)                    #for matrix multiplication

array([[ 752,  131],
       [3989,  444]])

**Concatinating and staking of arrays**

In [ ]:
y1=np.array([[4,85,7],[5,25,69]])

y2=np.array([[5,1,4],[1,56,6]])

In [ ]:
y1

array([[ 4, 85,  7],
       [ 5, 25, 69]])

In [ ]:
y2

array([[ 5,  1,  4],
       [ 1, 56,  6]])

In [ ]:
np.concatenate([y1,y2])                             # row wise -- no of DIMENSION IS SAME AS ORIGINAL ARRAYS

np.concatenate([y1,y2],axis=1)                      # column wise -- no of DIMENSION IS SAME AS ORIGINAL ARRAYS

array([[ 4, 85,  7,  5,  1,  4],
       [ 5, 25, 69,  1, 56,  6]])

In [ ]:
np.stack([y1,y2])                                  # DIMENSION INCREASES

array([[[ 4, 85,  7],
        [ 5, 25, 69]],

       [[ 5,  1,  4],
        [ 1, 56,  6]]])

In [ ]:
np.hstack([y1,y2])                                #same as concantenate with axis 1               #dimension doesnt get changed

array([[ 4, 85,  7,  5,  1,  4],
       [ 5, 25, 69,  1, 56,  6]])

In [ ]:
np.vstack([y1,y2])                                # stacks based on the position            #dimension doesnt get changed    axis=0

array([[ 4, 85,  7],
       [ 5, 25, 69],
       [ 5,  1,  4],
       [ 1, 56,  6]])